import React from "react";
import { Link } from "react-router-dom";

const technicalModules = [
  { name: "C Programming", path: "cnotes", icon: "C" },
  { name: "C++ Programming", path: "cpp", icon: "C++" },
  { name: "Java Programming", path: "java", icon: "☕" },
  { name: "Python Programming", path: "python", icon: "🐍" },
  { name: "DSA", path: "dsa", icon: "📈" },
  { name: "DBMS", path: "dbms", icon: "🗃️" },
  { name: "Operating Systems", path: "os", icon: "🖥️" },
  { name: "Computer Networks", path: "cn", icon: "🌐" },
];

export default function Technical() {
  return (
    <div className="max-w-7xl mx-auto p-6">
      <div className="text-center mb-16">
        <h1 className="text-5xl font-bold mb-4 text-white text-glow bg-clip-text text-transparent bg-gradient-to-r from-neon-blue to-neon-pink">
          Technical Module
        </h1>
        <p className="text-lg text-gray-400 max-w-3xl mx-auto">
          The Technical Module covers core subjects essential for placement preparation. 
          You’ll find programming notes, database concepts, operating systems, computer 
          networks, and data structures & algorithms. Each section is designed to help 
          you strengthen your fundamentals.
        </p>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-8">
        {technicalModules.map((module, idx) => (
          <Link
            key={idx}
            to={module.path}
            className="group relative bg-dark-card rounded-2xl p-6 border border-neon-pink/20 hover:border-neon-pink transition-all duration-300 transform hover:-translate-y-2 h-48 flex flex-col justify-between"
          >
            <div className="absolute top-0 left-0 w-full h-full rounded-2xl bg-gradient-to-r from-neon-blue to-neon-pink opacity-0 group-hover:opacity-10 transition duration-500 blur-md"></div>
            <div className="relative z-10 flex flex-col h-full">
              <div className="text-4xl font-bold text-neon-pink text-glow mb-4">{module.icon}</div>
              <h2 className="text-xl font-semibold text-white flex-grow">{module.name}</h2>
              <span className="mt-auto inline-block text-neon-blue font-bold group-hover:text-glow transition-all">
                Learn →
              </span>
            </div>
          </Link>
        ))}
      </div>

      {/* --- Coding Platform Section --- */}
      <div className="mt-24 pt-12 border-t-2 border-dashed border-neon-blue/20">
        <div className="max-w-3xl mx-auto text-center">
            <h2 className="text-4xl font-bold text-center mb-4 text-neon-blue text-glow">
                Coding Challenge 💻
            </h2>
            <p className="text-lg text-gray-400 mb-8">
                Solve real interview-style coding problems generated by AI. Write your code in our interactive editor and get instant feedback on your solution.
            </p>
            <Link
                to="/technical/coding-levels"
                className="inline-block bg-neon-blue text-black font-bold py-3 px-8 rounded-lg shadow-lg hover:scale-105 transition-transform animate-glow text-xl"
            >
                Start Coding Practice
            </Link>
        </div>
      </div>
    </div>
  );
}