// src/pages/Technical.jsx
import { Link } from "react-router-dom";

const technicalModules = [
  { name: "C Programming Notes", path: "cnotes" },
  { name: "C++ Programming Notes", path: "cpp" },
  { name: "Java Programming Notes", path: "java" },
  { name: "Python Programming Notes", path: "python" },
  { name: "DSA Notes", path: "dsa" },
  { name: "DBMS Notes", path: "dbms" },
  { name: "OS Notes", path: "os" },
  { name: "CN Notes", path: "cn" },
];

export default function Technical() {
  return (
    <div className="max-w-6xl mx-auto p-6">
      <h1 className="text-4xl font-bold mb-6 text-center text-blue-700">
        Technical Module
      </h1>
      <p className="mb-10 text-center text-lg text-gray-700 max-w-2xl mx-auto">
        The Technical Module covers core subjects essential for placement preparation. 
        You’ll find programming notes, database concepts, operating systems, computer 
        networks, and data structures & algorithms. Each section is designed to help 
        you strengthen your fundamentals and practice key concepts frequently asked 
        in interviews and exams.
      </p>
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
        {technicalModules.map((module, idx) => (
          <div
            key={idx}
            className="bg-gradient-to-r from-yellow-200 to-pink-300 
                      p-6 rounded-lg shadow hover:scale-105 transform transition
                      h-40 flex flex-col justify-between"
          >
            <h2 className="text-lg font-semibold">{module.name}</h2>
            <Link
              to={module.path}
              className="text-blue-600 hover:underline font-medium mt-2"
            >
              Learn →
            </Link>
          </div>
        ))}
      </div>

      {/* --- Coding Platform Section --- */}
        <div className="mt-16 pt-8 border-t-2 border-dashed border-gray-300">
            <h2 className="text-3xl font-bold text-center mb-6 text-indigo-600">
                Coding Challenge 💻
            </h2>
            <div className="max-w-2xl mx-auto text-center">
                <p className="text-lg text-gray-700 mb-6">
                    Solve real interview-style coding problems generated by AI. Write your code in our interactive editor and get instant feedback on your solution.
                </p>
                <Link
                    to="/technical/coding-levels" // <-- UPDATE THIS LINK
                    className="inline-block bg-indigo-600 text-white font-bold py-3 px-8 rounded-lg hover:bg-indigo-700 transition-transform transform hover:scale-105 text-xl"
                >
                    Start Coding Practice
                </Link>
            </div>
        </div>
    </div>
  );
}